DROP TABLE `USER`;
DROP TABLE `TOPIC`;
DROP TABLE `POST`;
DROP TABLE `COMMENT`;
DROP TABLE `SUBSCRIBE`;

CREATE TABLE IF NOT EXISTS `USER` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `username` varchar(50) NOT NULL,
    `create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `update_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS `TOPIC` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `description` TINYTEXT,
    `create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `update_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS `POST` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `content` LONGTEXT,
    `topicId` INT NOT NULL,
    `authorId` INT NOT NULL,
    `create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `update_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS `COMMENT` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `comment` VARCHAR(255),
    `postId` INT NOT NULL,
    `authorId` INT NOT NULL,
    `create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `update_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS `SUBSCRIBE` (
    `subscriberId` INT NOT NULL,
    `topicId` INT NOT NULL,
    `create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `update_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE `POST` ADD FOREIGN KEY (`topicId`) REFERENCES `TOPIC` (`id`);
ALTER TABLE `POST` ADD FOREIGN KEY (`authorId`) REFERENCES `USER` (`id`);
ALTER TABLE `COMMENT` ADD FOREIGN KEY (`postId`) REFERENCES `POST` (`id`);
ALTER TABLE `COMMENT` ADD FOREIGN KEY (`authorId`) REFERENCES `USER` (`id`);
ALTER TABLE `SUBSCRIBE` ADD FOREIGN KEY (`subscriberId`) REFERENCES `USER` (`id`);
ALTER TABLE `SUBSCRIBE` ADD FOREIGN KEY (`topicId`) REFERENCES `TOPIC` (`id`);

